### PR TITLE
Before importing an OpenPGP certificate, lint it

### LINKED ISSUE #1974: Importing a key has no verbosity information, unhelpful error message
I am attempting to import a repo key:
```
[root@c08aac51c007 /]# rpm --import gpg.key 
error: gpg.key: key 1 import failed.
[root@c08aac51c007 /]# rpm -v --import gpg.key 
error: gpg.key: key 1 import failed.
```
Where gpg.key is a local key. This also happens with remote URLs. I would have expected that it actually gives me an indication what the problem with the key is, or at least give me a hint what process/helper to check to further debug..

I am not particularly interested in why this particular key is failing (I assume it's the subkey enforcement changes) but without any indication for a reason, it's a bad UX.

### PR DESCRIPTION
**Pull request by nwalfield**
When importing an OpenPGP certificate, lint the certificate to show
the user possible issues.  Fail if the certificate is completely
unusable.  Using the Sequoia backend, this yields, for instance:

  $ ./rpmkeys --import tests/data/keys/alice-revoked-subkey.asc
  Certificate B3A771BFEB04E625:
    Subkey 1F71177215217EE0 was revoked: Key material has been compromised, it was the maid
    Certificate does not have any usable signing keys

Fixes #1974.

### CODE REVIEW

**Comment by nwalfield** [comment]
Note: this change includes [a stub implementation for the internal OpenPGP parser](https://github.com/nwalfield/rpm/commit/96278d3b9a616f053ea9526dbde93caee27629f0#diff-1b8795f690eee3ed483f0ce64cd81e4d42c681a13c98314a3250c4fac5159485R1349-R1353), whose feature development is frozen; this feature only works with the Sequoia backend.

File: lib/rpmts.c [hunk 1]
```diff
@@ -615,6 +616,16 @@ rpmRC rpmtsImportPubkey(const rpmts ts, const unsigned char * pkt, size_t pktlen
     if (txn == NULL)
 	return rc;
 
+    krc = pgpPubKeyLint(pkt, pktlen, &lints);
+    if (lints) {
+	fprintf(stderr, "%s\n", lints);
```
Comment (pmatilai) [inline lib/rpmts.c:621]: We can't really use fprintf() from librpm because it's a PITA for API users.

Rpm generally follows the "no news is good news" principle, and while enabling extra output with `-v` (for verbose) would fit, RPMLOG_INFO and NOTICE end up outputting to stdout which is a different kind of pain. I'd suggest using rpmlog() with log level based on `krc` - on error use RPMLOG_ERR and otherwise RPMLOG_DEBUG, that's the common workaround.

Comment (pmatilai) [reply lib/rpmts.c:621]: It wasn't clear to me from the sample output + code that the lint messages are always warnings. If that is the case then RPMLOG_WARNING is the right thing to do, but we don't want "considering/linting key foo" style messages visible by default.

Comment (nwalfield) [reply lib/rpmts.c:621]: > we don't want "considering/linting key foo" style messages visible 

Sorry about that, the "Consider..." lines are local debug output that I forgot to remove.  (I was confused about why I wasn't seeing any output, before I realized I needed two -vv's.)

> It wasn't clear to me from the sample output + code that the lint messages are always warnings. 

There are two cases where I generate lints: for unusable certificates, and suspicious certificates.  A suspicious certificate might be one where the primary key is okay, but a signing-capable subkey uses SHA-1 and is thus considered invalid.

Comment (nwalfield) [reply lib/rpmts.c:621]: A subkey that uses SHA-1 is ignored, but that doesn't mean the primary key can't be used to verify signatures.  That's why that case is a warning and not an error.

Comment (pmatilai) [reply lib/rpmts.c:621]: Sure, in that case RPMLOG_WARNING/ERROR, depending on krc is the right thing.

Comment (nwalfield) [reply lib/rpmts.c:621]: As far as I can tell, `RPMLOG_WARNING` log messages are only shown when `-vv` is passed to `rpm`.  Doesn't that mean in practice few people will actually see those warnings?

Comment (pmatilai) [reply lib/rpmts.c:621]: WARNING and ERROR level messages are practically always output, because, well, people need to see them. It's the levels above those that are dependent on -v/-vv.

File: lib/rpmts.c [hunk 2]
```diff
@@ -615,6 +616,20 @@ rpmRC rpmtsImportPubkey(const rpmts ts, const unsigned char * pkt, size_t pktlen
     if (txn == NULL)
 	return rc;
 
+    krc = pgpPubKeyLint(pkt, pktlen, &lints);
+    if (lints) {
+        if (krc != RPMRC_OK) {
+            rpmlog(RPMLOG_ERR, _("Linting certificate: %s\n"), lints);
+        } else {
+            rpmlog(RPMLOG_WARNING, _("Linting certificate: %s\n"), lints);
```
Comment (pmatilai) [inline lib/rpmts.c:624]: I'd just leave the "Linting certificate" part out, and just emit whatever messages there are. These messages will be seen by regular users, and I think "lint" as a verb isn't widely known outside software development circles. Might be difficult to translate as well.

Comment (nwalfield) [reply lib/rpmts.c]: Good idea.
